import type { Metadata } from "next";
import {
  Geist,
  Pixelify_Sans,
} from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const pixelfy = Pixelify_Sans({
  variable: "--pixel-font",
  subsets: ["latin"],
  weight: "400",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" className={`${pixelfy.variable}`}>
      <body className={`${pixelfy.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
