import type { Metadata } from "next";
import { Pixelify_Sans } from 'next/font/google'
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import React from "react";



const pixelfy = Pixelify_Sans({
  variable: "--pixel-font",
  subsets: ["latin"],
  weight: "400",
  display: 'swap',
  preload: false,
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
      <html lang="en" className={pixelfy.variable}>
      <body className={`${pixelfy.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
